version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dotnet-server
    container_name: my-dotnet-server
    volumes:
      - ./:/source/lauchpadApp
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql-server
    container_name: my-mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nscc
      MYSQL_DATABASE: dbApp
      MYSQL_USER: w0452987
      MYSQL_PASSWORD: saliba
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: my-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    web-root:
      driver: local